admin:
  object_image_md: "150x150"
  object_image_md_data_src: "holder.js/150x150?theme=gray&text=Image"
  object_image_sm: "35x35"
  object_image_sm_data_src: "holder.js/35x35?theme=gray&text=Image&size=5"
  user_avatar_md: "150x150"
  user_avatar_md_data_src: "holder.js/150x150?theme=gray&text=Avatar"
  user_avatar_sm: "35x35"
  user_avatar_sm_data_src: "holder.js/35x35?theme=gray&text=Avatar&size=5"
trainee:
  object_image_lg: "220x220"
  object_image_lg_data_src: "holder.js/220x220?theme=gray&text=Image"
  object_image_md: "100x100"
  object_image_md_data_src: "holder.js/100x100?theme=gray&text=Image"
  object_image_sm: "40x40"
  object_image_sm_data_src: "holder.js/40x40?theme=gray&text=Image&size=5"
  user_avatar_lg: "220x220"
  user_avatar_lg_data_src: "holder.js/220x220?theme=gray&text=Avatar"
  user_avatar_md: "100x100"
  user_avatar_md_data_src: "holder.js/100x100?theme=gray&text=Avatar"
  user_avatar_sm: "40x40"
  user_avatar_sm_data_src: "holder.js/40x40?theme=gray&text=Avatar&size=5"
